# Generated by Django 4.2.6 on 2023-11-12 12:19

from django.db import migrations, models
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="uid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
