# Generated by Django 4.2.6 on 2023-10-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_organization"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "verbose_name": "организация",
                "verbose_name_plural": "организации",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-pk"],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
    ]
