# Generated by Django 4.2.6 on 2023-11-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Актуальная версия"),
        ),
    ]
