# Generated by Django 4.2.6 on 2023-11-10 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_version_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "verbose_name": "Контактные данные",
                "verbose_name_plural": "Контактные данные",
            },
        ),
    ]
