# Generated by Django 4.2.6 on 2023-11-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_organization_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активны"),
            preserve_default=False,
        ),
    ]
